apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iones-persistent-storage
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Gi